### ISSUE TITLE
Bad Access When Printing Empty HashTable

### ISSUE THREAD

**Issue by mlacapra** [sanoff/Anoff_CSCI2270_FinalProject#1]
When I run the program without a command line argument, the code generates bad access when I select the option to print the empty hashTable.

**Comment by sanoff** [comment]
Is this for the phase 3? And I might need to make an adjustment, it looks
like the code only generates the hash table in the in file. I can make the
adjustment for it to generate the empty one if there isn't a CLA as well.

**Comment by mlacapra** [comment]
Yes, this is for phase 3. In the documentation it is listed that I can run the program with or without a text file, so I tested both cases. When the program is run with the text file, there are no issues.

**Comment by sanoff** [comment]
Oh ok. Well the readme looks like it rolled back wen I updated it and
didn't include that bug that I mentioned later on. We can do one of tree
things, I can fix it, you can fix it for the contribution, or I can update
the readme again to account for it.

**Comment by mlacapra** [comment]
Whatever's easiest for you, I don't mind fixing it if you would like me to

**Comment by sanoff** [comment]
I mean either way it'll go down as a bug fixed theouh collaboration, I can
do it tomorrow though

**Comment by sanoff** [comment]
Resolved in most recent commit.
