### ISSUE TITLE
A couple things to consider

### ISSUE THREAD

**Issue by Jbuehler22** [sanoff/Anoff_CSCI2270_FinalProject#2]
1) the way you are creating a new instance of a movie, in printInventory() year will never be null.

2) found should be created in the find movie function, not associated with the movie struct. You don't even use it anyway.

3) you can't fill up a hash table. it's an array of linked lists, and you can always add to a linked list. even if you double the array size, you'll still have collisions that the linked list takes care of.

**Comment by sanoff** [comment]
PrintInventory has a case for null for future builds.
Found was meant to be used later on for a sorting algorithm, but removed in this commit.
Fill up isn't exactly what I was going for... It's more of an efficiency algorithm - A hash table's efficiency directly correlates to how many collisions there are, not if there's "space" or not. That's the issue the function is trying to resolve - an issue of efficiency. By upping the Hashsum and the array size, there are fewer collisions, and thus fewer linked lists to sort through.
